package AssignmentTwo;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;

public class GetClient {
    public static void main (String [] args) {
        // lamport clock
        String server_name = args[0]; // "http://servername.domain.domain:portnumber", "http://servername:portnumber",
                                     // "servername:portnumber"
        int lamport_clock = 0; // lamport clock initialised at 0 to begin


    }
}